apiVersion: v1
kind: ConfigMap
metadata:
  name: forfarm-config
  namespace: forfarm
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "forfarmdb"
  POSTGRES_HOST: "postgres-service.forfarm.svc.cluster.local"
  DATABASE_URL: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)?sslmode=disable"

  RABBITMQ_USER: "user"
  RABBITMQ_HOST: "rabbitmq-service.forfarm.svc.cluster.local"
  RABBITMQ_URL: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):5672/"

  # Backend Config
  PORT: "8000"
  WEATHER_FETCH_INTERVAL: "60m"
  OPENWEATHER_CACHE_TTL: "15m"
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID"
  GOOGLE_REDIRECT_URL: "https://your-domain.com/auth/login/google"

  NEXT_PUBLIC_BACKEND_URL: "http://backend-service.forfarm.svc.cluster.local:8000"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: "NEXT_PUBLIC_GOOGLE_CLIENT_ID"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"

  # GCS Config
  GCS_BUCKET_NAME: "YOUR_GCS_BUCKET_NAME"
  # GCS_SERVICE_ACCOUNT_KEY_PATH: "/etc/gcs-secrets/key.json"
