apiVersion: apps/v1
kind: Deployment
metadata:
  name: forfarm-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forfarm-frontend
  template:
    metadata:
      labels:
        app: forfarm-frontend
    spec:
      containers:
        - name: frontend
          image: sosokker/forfarm-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://forfarm-backend-service:8000"
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: forfarm-secrets
                  key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
            - name: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: forfarm-secrets
                  key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "750m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
