apiVersion: v1
kind: Secret
metadata:
  name: forfarm-secrets
  namespace: forfarm
type: Opaque
data:
  # Use: echo -n "your_password" | base64
  POSTGRES_PASSWORD: <base64-encoded-db-password>
  RABBITMQ_PASSWORD: <base64-encoded-rabbitmq-password>
  JWT_SECRET_KEY: <base64-encoded-jwt-secret>
  GOOGLE_CLIENT_SECRET: <base64-encoded-google-client-secret>
  OPENWEATHER_API_KEY: <base64-encoded-openweather-key>
  GEMINI_API_KEY: <base64-encoded-gemini-key>
  GCS_SERVICE_ACCOUNT_KEY_JSON: <base64-encoded-gcs-key-json>
